name: Clean PR Deployment

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Remove from gh-pages
        run: |
          rm -rfv "gh-pages/pr${{ github.event.number }}" || true
      - name: Make commit to deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./pr${{ github.event.number }}
          git commit -m "pr${{ github.event.number }} build"
          git push origin gh-pages
        working-directory: gh-pages
