name: Deploy PR

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Set git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Yarn install
        run: |
          yarn install --immutable --immutable-cache
      - name: Setup .env
        run: |
          printf '%s' "$ENVFILE" > apps/frontend/.env.local
        env:
          ENVFILE: ${{ secrets.ENVFILE }}
      - name: Build genshin-optimizer
        run: |
          NX_URL_GITHUB_GO_CURRENT_VERSION="https://github.com/${{ github.repository }}/commit/$(git rev-parse HEAD)" \
          yarn run nx run frontend:build:production --base-href=""
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Move to gh-pages
        run: |
          mkdir --parents "gh-pages/pr${{ github.event.issue.number }}"
          rm -rfv "gh-pages/pr${{ github.event.issue.number }}" || true
          mv "dist/apps/frontend" "gh-pages/pr${{ github.event.issue.number }}"
      - name: Make commit to deploy
        run: |
          git add ./pr${{ github.event.issue.number }}
          git commit -m "build pr${{ github.event.issue.number }} ${{ steps.branch-deploy.outputs.ref }}"
          git push origin gh-pages
        working-directory: gh-pages
      - name: Update deployment message
        run: |
          echo "DEPLOY_MESSAGE=Deployed to https://${{ github.repository_owner }}.github.io/${GITHUB_REPOSITORY#*/}/pr${{ github.event.issue.number }}" >> $GITHUB_ENV
