# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - go-next

on:
  push:
    branches:
      - van/azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: yarn install, build, and test
        run: |
          yarn install
          yarn run nx run frontend:build:production
          yarn run nx run-many --target=test

      - name: Prune dev dependencies
        run: yarn workspaces focus --production

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x .git libs/dm/Texture2D tmp libs/dm/GenshinData/.git libs/dm/GenshinData/Readable libs/dm/GenshinData/BinOutput libs/GenshinData/Subtitle libs/sr-dm/StarRailData/ node_modules/.cache

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'go-next'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C03995DA9BC84C0DA81F6736A5C618B6 }}
